// Development-only samples generated by RiasecPublicProjectionService from synthetic scores.
// Content comes from the backend canonical assets; this is not a user's persisted report.
import { notFound } from "next/navigation";
import { RiasecResultShell } from "@/components/result/riasec/RiasecResultShell";
import { assembleRiasecResultViewModel } from "@/lib/riasec/resultAssembler";
import type { ReportResponse } from "@/lib/api/v0_3";
import samples from "./backend-samples.json";

export const metadata = { title: "本地报告样例 · Local report sample" };

export default async function Preview({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ form?: string; mode?: string }>;
}) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { locale: rawLocale } = await params;
  const { form, mode } = await searchParams;
  const locale = rawLocale === "en" ? "en" : "zh";
  const key =
    `${locale === "zh" ? "zh-CN" : "en"}-${form === "60" ? "60" : "140"}` as keyof typeof samples;
  const vm = assembleRiasecResultViewModel(
    {
      scale_code: "RIASEC",
      type_code: "IAS",
      riasec_public_projection_v2: samples[key],
    } as unknown as ReportResponse,
    locale,
  );
  return (
    <main
      style={{ maxWidth: 1200, margin: "0 auto", padding: "16px 24px 48px" }}
    >
      <RiasecResultShell
        locale={locale}
        viewModel={vm}
        displayMode={mode === "static" ? "static" : "interactive"}
      />
    </main>
  );
}
